// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types';

const SUPABASE_URL = "https://shqzayolcawtaecabyai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNocXpheW9sY2F3dGFlY2FieWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3OTUzNDMsImV4cCI6MjA1NjM3MTM0M30.UP6qHrK0FVd3CKCMmu3XjwmE_bkJ9JlPpvVUNGxdb-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);